return {
  ["workshop-1079538195"]={
    configuration_options={
      beebox=true,
      birdcage=true,
      cartographydesk=true,
      cookpot=true,
      dragonflychest=true,
      dragonflyfurnace=true,
      endtable=true,
      firesuppressor=true,
      icebox=true,
      lightning_rod=true,
      meatrack=true,
      modsupport=false,
      moondial=true,
      mushroom_farm=true,
      mushroom_light=true,
      nightlight=true,
      perdshrine=true,
      pottedfern=true,
      rainometer=true,
      researchlab=true,
      researchlab2=true,
      researchlab3=true,
      researchlab4=true,
      resurrectionstatue=true,
      saltlick=true,
      scarecrow=true,
      sculptingtable=true,
      succulent_potted=true,
      townportal=true,
      treasurechest=true,
      wardrobe=true,
      winterometer=true 
    },
    enabled=true 
  },
  ["workshop-1139327644"]={
    configuration_options={
      OptionCheckingForFollowers=0.5,
      OptionHUDdown=0,
      OptionHUDhorizontal=0,
      OptionMaxFollowers=6 
    },
    enabled=true 
  },
  ["workshop-1166220990"]={ configuration_options={ attract=2, language=2 }, enabled=true },
  ["workshop-1173770304"]={ configuration_options={ language=2 }, enabled=true },
  ["workshop-1181077385"]={ configuration_options={  }, enabled=true },
  ["workshop-1204112832"]={ configuration_options={ language=2 }, enabled=true },
  ["workshop-1207269058"]={
    configuration_options={
      ddon=true,
      hbcolor="dynamic",
      hblength=10,
      hbpos=1,
      hbstyle="heart",
      value=true 
    },
    enabled=true 
  },
  ["workshop-1217385169"]={ configuration_options={  }, enabled=true },
  ["workshop-1242093526"]={ configuration_options={ glowcap=1, mushlight=1, winter_tree=0 }, enabled=true },
  ["workshop-353697884"]={ configuration_options={  }, enabled=true },
  ["workshop-356420397"]={ configuration_options={  }, enabled=true },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-375859599"]={
    configuration_options={
      divider=0,
      random_health_value=0,
      random_range=0,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-380423963"]={
    configuration_options={
      [""]=0,
      boulder_blue=0.5,
      boulder_purple=0.5,
      change_cave_loot=false,
      common_loot_charcoal=0,
      common_loot_flint=0.35,
      common_loot_rocks=0.35,
      cutlichen=0,
      durian=0,
      flintless_blue=0.5,
      flintless_purple=0.5,
      flintless_red=0.5,
      foliage=0,
      gears=0,
      goldvein_purple=0.5,
      goldvein_red=0.5,
      guano=0,
      ice=0,
      lightbulb=0,
      moon_green=0.5,
      moon_orange=0.5,
      moon_yellow=0.5,
      pinecone=0,
      rare_loot_bluegem=0.015,
      rare_loot_marble=0.015,
      rare_loot_redgem=0.015,
      rottenegg=0,
      seeds=0,
      spoiled_food=0,
      stalagmite_green=0.5,
      stalagmite_orange=0.5,
      stalagmite_yellow=0.5,
      uncommon_loot_goldnugget=0.05,
      uncommon_loot_mole=0.05,
      uncommon_loot_nitre=0.05,
      uncommon_loot_rabbit=0.05 
    },
    enabled=true 
  },
  ["workshop-382177939"]={
    configuration_options={ [""]=true, eightxten="5x16", workit="yep" },
    enabled=true 
  },
  ["workshop-439115156"]={
    configuration_options={
      avisual_musha="WSH",
      avisual_pirate="WLB",
      avisual_pirate_armor="pink",
      avisual_princess="WLR",
      badge_type=2,
      bodyguardwilson=0,
      craftgems="color",
      deathPenalty="off",
      dietmusha="normal",
      difficultdamage="newbie",
      difficultdamage_range="veasy",
      difficulthealth="easy",
      difficultmusic="dmusic_veasy",
      difficultover="monster1x",
      difficultrecipe="easy",
      difficultsanity="easy",
      difficultsleep="dsleep_veasy",
      difficulttired="dtired_veasy",
      favoritemusha="normal",
      frostblade3rd=1,
      incontainer=0,
      key=108,
      key10=110,
      key11=103,
      key12=116,
      key13=282,
      key14=283,
      key15=111,
      key2=114,
      key3=99,
      key4=120,
      key5=107,
      key6=122,
      key7=112,
      key8=118,
      key9=98,
      loudlightning="loud3",
      musha_incontainer=1,
      on_butterfly_shield=1,
      princess_taste="princess",
      shareitems=1,
      smartmusha="verysmart",
      stop_spawning=2 
    },
    enabled=true 
  },
  ["workshop-444438334"]={
    configuration_options={ backpackCategory="resources", funMode="yes", keybind=104, maxLights=2 },
    enabled=true 
  },
  ["workshop-458587300"]={ configuration_options={ Ownership=false, Travel_Cost=32 }, enabled=true },
  ["workshop-462372013"]={ configuration_options={  }, enabled=true },
  ["workshop-466732225"]={ configuration_options={  }, enabled=true },
  ["workshop-501385076"]={ configuration_options={  }, enabled=true },
  ["workshop-646227245"]={
    configuration_options={ hunger=1, item=1, language=2, level=5, speed=1, type=1 },
    enabled=true 
  },
  ["workshop-647370020"]={
    configuration_options={
      katanasbasedamage=50,
      shieldbasedamage=35,
      shieldspeed=12,
      spideybasedamage=1,
      spideybasehp=150,
      spideybasehpregen=1,
      spideybasehunger=100,
      spideybasehungerdrains=0.15,
      spideybasesanity=100 
    },
    enabled=true 
  },
  ["workshop-758532836"]={
    configuration_options={
      AUTOPAUSECONSOLE=false,
      AUTOPAUSEMAP=false,
      AUTOPAUSESINGLEPLAYERONLY=true,
      ENABLECLIENTPAUSE=false,
      ENABLEHOTKEY=false,
      KEYBOARDTOGGLEKEY="J" 
    },
    enabled=true 
  },
  ["workshop-831523966"]={ configuration_options={  }, enabled=true },
  ["workshop-949808360"]={
    configuration_options={
      ChargeKey=122,
      CheckKey=106,
      CrossEdge=false,
      DaggerLimit=false,
      DodgeKey=114,
      IcicleKey=99,
      Language=true 
    },
    enabled=true 
  } 
}